#MySQL 설정
spring:
  application:
    name: hhplus_3th_reserve
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dba
    username: root
    password: 595959
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port : 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
    admin:
      auto-create: true

logging:
  level:
    org.hhplus.reserve.interceptor: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true