version: '3.8'
services:
  #redis 셋팅
  redis:
    image: redis:latest
    container_name: redis_test
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  #DB MYSQL 셋팅
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 595959
      MYSQL_DATABASE: dba
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 595959
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mysql-data:
  redis_data:
